import "server-only";
import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { getEnv } from "@/lib/env";

/**
 * Where uploaded image bytes live. Only a local `file` driver exists; object storage (S3/R2) can be
 * added behind this interface without touching the services above it.
 */
export interface MediaStore {
  put(key: string, bytes: Buffer): Promise<void>;
  get(key: string): Promise<Buffer | null>;
  delete(key: string): Promise<void>;
}

/** Storage keys are generated by the app (`wedding/asset.ext`); never accept a caller-supplied path. */
const KEY_PATTERN = /^[a-f0-9-]{36}\/[a-f0-9-]{36}(-[0-9]{2,4})?\.(jpg|png|webp|mp3|m4a|ogg)$/;

export class FileMediaStore implements MediaStore {
  constructor(private readonly directory: string) {}

  private resolve(key: string): string {
    if (!KEY_PATTERN.test(key)) throw new Error("Invalid media key");
    return path.join(this.directory, key);
  }

  async put(key: string, bytes: Buffer): Promise<void> {
    const file = this.resolve(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, bytes);
  }

  async get(key: string): Promise<Buffer | null> {
    try {
      return await readFile(this.resolve(key));
    } catch {
      return null;
    }
  }

  async delete(key: string): Promise<void> {
    try {
      await unlink(this.resolve(key));
    } catch {
      // Already gone: deleting the database row is what matters.
    }
  }
}

let cached: MediaStore | undefined;

export function getMediaStore(): MediaStore {
  if (!cached) cached = new FileMediaStore(path.resolve(getEnv().MEDIA_FILE_DIR));
  return cached;
}

export const MIME_EXTENSION: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "audio/mpeg": "mp3",
  "audio/mp4": "m4a",
  "audio/ogg": "ogg",
};
